### ISSUE TITLE
Type Inference not working correctly for static methods, virtuals etc.

### ISSUE THREAD

**Issue by bennidi** [andreww2012/mongoose-zod#10]
I am trying your library and I get TypeScript errors in everything related to mongoose model extension (like statics, virtuals).

1. Static methods do not show up in Model
2. Instance methods can not be defined (compiler complains that only those properties already defined are allowed)
3. Virtuals do not show up in model, neither is `this` bound correctly

I thought it was because I am using TS 5 in my project. So I checked out your repo and installed all dependencies. Still the same. Basically the type inference does not work correctly.

<img width="1110" alt="CleanShot 2023-09-21 at 19 31 43@2x" src="https://github.com/andreww2012/mongoose-zod/assets/1842420/017238d0-d214-4436-b63b-5a8e43e78a5d">

**Comment by bennidi** [comment]
<img width="661" alt="CleanShot 2023-09-21 at 19 35 29@2x" src="https://github.com/andreww2012/mongoose-zod/assets/1842420/bc3d698e-01a4-4a2f-8035-aab569ab7495">

<img width="1089" alt="CleanShot 2023-09-21 at 19 36 32@2x" src="https://github.com/andreww2012/mongoose-zod/assets/1842420/5de325be-fd4b-4c63-8b04-0434d781f542">

**Comment by andreww2012** [comment]
Hello, could you tell what `mongoose` version is used in any of your repositories on the screenshots?

You can find that out by running `npx -y qnm mongoose` ([about `qnm`](https://www.npmjs.com/package/qnm)).

I recently discovered that `mongoose-zod` is actually incompatible with `mongoose`>=6.8 since [they've changed `SchemaOptions` type signature](https://github.com/Automattic/mongoose/commit/68c0329f908a284e93afafede0bd42bd73c70efa?diff=split#diff-ddef51cacff5851e3055f40c3e1fa31434b58d9fc081e101199136fbd526d34eL10-L13) that is used in this package.

**Comment by bennidi** [comment]
Yes, that is indeed the reason. Fixing the version to 6.6.5 did the trick.
Makes me a happy developer again. Great effort that you did here.

Do you plan to support mongoose 7 anytime soon?

I wish I could help but I was trying to figure out the code and types already but it is rather advanced and would take me much time to understand.

**Comment by andreww2012** [comment]
Glad you made it work 👍

> Do you plan to support mongoose 7 anytime soon?

Yes, see #9. Hopefully in October. I need to first support 6.8 and fix some found bugs.
