### ISSUE TITLE
Add example for models with relationships or embedded objects (subdocuments)

### ISSUE THREAD

**Issue by bennidi** [andreww2012/mongoose-zod#12]
I think the title says it all. Since I am new to mongoose and zod I am struggling with how to build a model that has embedded documents as well as relationships.
Maybe I am just being a bit stupid?

I assume you have some code samples at hand for this. Maybe you can share those?

**Comment by angelhdzmultimedia** [comment]
As the OP, I need help working with relations.

I've navigated almost every option in the zod/mongoose schema, and can't see how to set the `ref`.

In Prisma is very easy to do, but I no longer want to work with Prisma because want to do everything with TypeScript code (also don't want to execute `prisma generate` every time I make a change in the schema...)



I have a UserValidationSchema (zod) with a property `profile` which is a UserProfileValidationSchema (zod).
When creating a user in users collection, it should create a profile in user-profiles collection, and when retrieving a user from users, it should bring the corresponding profile from user-profiles. 

I will appreciate a lot any info. Thank you!

**Edit**
I found it!!!  🔥🤯
![image](https://github.com/andreww2012/mongoose-zod/assets/10191085/27dcf199-a96f-4d5f-8446-7b918f243873)

**Comment by andreww2012** [comment]
Hello, please see https://github.com/andreww2012/mongoose-zod/issues/5#issuecomment-1518685724
Defining relationships is fully handled by `mongoose`. Remember that `mongoose-zod` is just a convenient constructor of mongoose schemas, and if you can't find a feature that is supported by `mongoose-zod`, you should go down to `mongoose` level. Perhaps explicitly mentioning handling references in the documentation is a good idea. 👍
